# Generated by Django 3.2.3 on 2021-05-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuentryname', models.CharField(max_length=200)),
                ('counterypepol', models.IntegerField()),
                ('counterycity', models.IntegerField()),
                ('counteryseles', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='cotogery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categourey', models.CharField(max_length=200)),
            ],
        ),
    ]
