# Generated by Django 3.2.3 on 2021-05-29 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ecom', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chart',
            new_name='mychart',
        ),
    ]
